### ISSUE TITLE
Restart of rtp-engine.service causes sidecar to stop updating SBC of status 

### ISSUE THREAD

**Issue by ajukes** [jambonz/sbc-rtpengine-sidecar#8]
When RTP engine is restarted the status does not propagate to SBCs.

restarting sbc-rtpengine-sidecar fixes issue

**Comment by ajukes** [comment]
As requested, please find error log below when restarting/reloading rtpengine.service. The sidecar app does not recover.

1|sbc-rtpengine-sidecar  | {"level":50, "time": "2022-08-01T20:24:53.131Z","pid":34738,"hostname":"ip-172-31-5-85","err":{"type":"Error","message":"WebSocket is not open: readyState 3 (CLOSED)","stack":"Error: WebSocket is not open: readyState 3 (CLOSED)\n    at sendAfterClose (/home/admin/apps/sbc-rtpengine-sidecar/node_modules/ws/lib/websocket.js:967:17)\n    at WebSocket.send (/home/admin/apps/sbc-rtpengine-sidecar/node_modules/ws/lib/websocket.js:405:7)\n    at /home/admin/apps/sbc-rtpengine-sidecar/node_modules/rtpengine-client/lib/BaseClient.js:56:21\n    at new Promise (<anonymous>)\n    at WsClient.send_internal (/home/admin/apps/sbc-rtpengine-sidecar/node_modules/rtpengine-client/lib/BaseClient.js:27:12)\n    at WsClient.<computed> [as statistics] (/home/admin/apps/sbc-rtpengine-sidecar/node_modules/rtpengine-client/lib/WsClient.js:22:17)\n    at getStats (/home/admin/apps/sbc-rtpengine-sidecar/lib/sbc-pinger.js:11:35)\n    at pingProxies (/home/admin/apps/sbc-rtpengine-sidecar/lib/sbc-pinger.js:86:30)\n    at listOnTimeout (node:internal/timers:559:17)\n    at processTimers (node:internal/timers:502:7)"},"msg":"Error retrieving statistics"}
